version: "3"

services:
  traffic_model_api_1:
    image: traffic_model:api-latest
    container_name: traffic_model_api_1
    restart: always
    ports:
      - "8001:8000"
    tty: true
    volumes:
      - ~/airflow/mlops_data_store/${ENCODERS_PATH}:/home/mlops/resources/encoders
      - ~/airflow/mlops_data_store/${MODEL_PATH}:/home/mlops/resources/model
    environment:
      ML_METADATA_URL: mysql+pymysql://root:root@mariadb-mlops-study/mlops_project_meta
      MODEL_NAME: ${MODEL_NAME}
      MODEL_VERSION: ${MODEL_VERSION}
    networks:
      mlops_study_network:
  traffic_model_api_2:
    image: traffic_model:api-latest
    container_name: traffic_model_api_2
    restart: always
    ports:
      - "8002:8000"
    tty: true
    volumes:
      - ~/airflow/mlops_data_store/${ENCODERS_PATH}:/home/mlops/resources/encoders
      - ~/airflow/mlops_data_store/${MODEL_PATH}:/home/mlops/resources/model
    environment:
      ML_METADATA_URL: mysql+pymysql://root:root@mariadb-mlops-study/mlops_project_meta
      MODEL_NAME: ${MODEL_NAME}
      MODEL_VERSION: ${MODEL_VERSION}
    networks:
      mlops_study_network:
networks:
  mlops_study_network:
    name: mlops_study_network
    external: true